language: node_js
install:
  - npm install
  - npm install -g codecov

node_js:
  - "10"
  - "12"
  - "14"

script:
  - npm run lint
  - npm run check-dts
  - npm run coverage
  - npm run docs

after_script:
  - if [[ `node --version` == *12* ]]; then codecov; fi