name: Node.js CI

on:
- push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14, 16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: ''
    - run: npm i
    - run: npm run lint
    - run: npm run check-dts || exit 0
    - run: npm run coverage
    - run: npm run docs
    - run: npm t
    - uses: codecov/codecov-action@v2
      if: matrix.node-version == 16